version: '3.1'
services:
  app:
    build: .
    volumes:
      - .:/app
      - app_assets:/app/public/assets/
      - app_bundle:/app/vendor/bundle
      - app_file_storage:/app/public/system/
      - app_logs:/app/logs/
      # For deploy with capistrano, pass the .ssh/config and ssh-agent
      - ~/.ssh:/root/.ssh
      - $SSH_AUTH_SOCK:/ssh-agent
    env_file:
      - .env
      - .env.development
    depends_on:
      - pg
      - redis
    ports:
      - 3000:3000
    links:
      - pg
      - redis
    command: bundle exec puma
  worker:
    build: .
    volumes:
      - .:/app
      - app_assets:/app/public/assets/
      - app_bundle:/app/vendor/bundle
      - app_file_storage:/app/public/system/
      - app_logs:/app/logs/
    env_file:
      - .env
      - .env.development
    depends_on:
      - app
      - pg
      - redis
    links:
      - pg
      - redis
    command: bundle exec sidekiq
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  app_assets: {}
  app_bundle: {}
  app_file_storage: {}
  app_logs: {}
  pg-data: {}
  redis-data: {}
